export const FORM_INPUT_BODY_INFORMATION = 'FORM_INPUT_BODY_INFORMATION';
export const INPUT_BODY_INFORMATION_REQUEST = 'INPUT_BODY_INFORMATION_REQUEST';
export const INPUT_BODY_INFORMATION_RESPONSE = 'INPUT_BODY_INFORMATION_RESPONSE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_RESPONSE = 'SIGN_UP_RESPONSE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_RESPONSE = 'GET_PROFILE_RESPONSE';